//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fast.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fast.Web.Resources.MessageResources", typeof(MessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maaf akun anda terlock, silahkan hubungi TI.
        /// </summary>
        public static string AccountLocked {
            get {
                return ResourceManager.GetString("AccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maaf akun anda Non Active, silahkan hubungi TI.
        /// </summary>
        public static string AccountNonActive {
            get {
                return ResourceManager.GetString("AccountNonActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akun anda masih Pending (dalam moderasi) kantor Pusat.
        /// </summary>
        public static string AccountPending {
            get {
                return ResourceManager.GetString("AccountPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} already exist in the system.
        /// </summary>
        public static string DataExist {
            get {
                return ResourceManager.GetString("DataExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data telah disimpan.
        /// </summary>
        public static string DataHasBeenSaved {
            get {
                return ResourceManager.GetString("DataHasBeenSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete failed. Please check your user logs..
        /// </summary>
        public static string DeleteFailed {
            get {
                return ResourceManager.GetString("DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data has been deleted successfully.
        /// </summary>
        public static string DeleteSucceed {
            get {
                return ResourceManager.GetString("DeleteSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File telah gagal dihapus.
        /// </summary>
        public static string FileDeleteFailed {
            get {
                return ResourceManager.GetString("FileDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File telah berhasil dihapus.
        /// </summary>
        public static string FileDeleteSucceed {
            get {
                return ResourceManager.GetString("FileDeleteSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password tidak valid.
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username tidak ditemukan.
        /// </summary>
        public static string InvalidUsername {
            get {
                return ResourceManager.GetString("InvalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added new {0} {1}.
        /// </summary>
        public static string LogAdd {
            get {
                return ResourceManager.GetString("LogAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added category 3D {0}.
        /// </summary>
        public static string LogAddCategory3D {
            get {
                return ResourceManager.GetString("LogAddCategory3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added category PDF {0}.
        /// </summary>
        public static string LogAddCategoryPDF {
            get {
                return ResourceManager.GetString("LogAddCategoryPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added new Gallery 3D {0}.
        /// </summary>
        public static string LogAddGallery3D {
            get {
                return ResourceManager.GetString("LogAddGallery3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Master 3D {0}.
        /// </summary>
        public static string LogAddMaster3D {
            get {
                return ResourceManager.GetString("LogAddMaster3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added new master media {0}.
        /// </summary>
        public static string LogAddMasterMedia {
            get {
                return ResourceManager.GetString("LogAddMasterMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added master pdf {0}.
        /// </summary>
        public static string LogAddMasterPDF {
            get {
                return ResourceManager.GetString("LogAddMasterPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added new module {0}.
        /// </summary>
        public static string LogAddModule {
            get {
                return ResourceManager.GetString("LogAddModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added permission {0} to role {1}.
        /// </summary>
        public static string LogAddPermission {
            get {
                return ResourceManager.GetString("LogAddPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added new project {0}.
        /// </summary>
        public static string LogAddProject {
            get {
                return ResourceManager.GetString("LogAddProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added new role {0}.
        /// </summary>
        public static string LogAddRole {
            get {
                return ResourceManager.GetString("LogAddRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added new user {0}.
        /// </summary>
        public static string LogAddUser {
            get {
                return ResourceManager.GetString("LogAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted {0} {1}.
        /// </summary>
        public static string LogDelete {
            get {
                return ResourceManager.GetString("LogDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted category 3D {0}.
        /// </summary>
        public static string LogDeleteCategory3D {
            get {
                return ResourceManager.GetString("LogDeleteCategory3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted category PDF {0}.
        /// </summary>
        public static string LogDeleteCategoryPDF {
            get {
                return ResourceManager.GetString("LogDeleteCategoryPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Gallery 3D {0}.
        /// </summary>
        public static string LogDeleteGallery3D {
            get {
                return ResourceManager.GetString("LogDeleteGallery3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Master 3D {0}.
        /// </summary>
        public static string LogDeleteMaster3D {
            get {
                return ResourceManager.GetString("LogDeleteMaster3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted master media {0}.
        /// </summary>
        public static string LogDeleteMasterMedia {
            get {
                return ResourceManager.GetString("LogDeleteMasterMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted master pdf {0}.
        /// </summary>
        public static string LogDeleteMasterPDF {
            get {
                return ResourceManager.GetString("LogDeleteMasterPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted module {0}.
        /// </summary>
        public static string LogDeleteModule {
            get {
                return ResourceManager.GetString("LogDeleteModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted permission {0} from role {1}.
        /// </summary>
        public static string LogDeletePermission {
            get {
                return ResourceManager.GetString("LogDeletePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted project {0}.
        /// </summary>
        public static string LogDeleteProject {
            get {
                return ResourceManager.GetString("LogDeleteProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted role {0}.
        /// </summary>
        public static string LogDeleteRole {
            get {
                return ResourceManager.GetString("LogDeleteRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted user {0}.
        /// </summary>
        public static string LogDeleteUser {
            get {
                return ResourceManager.GetString("LogDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited {0} {1}.
        /// </summary>
        public static string LogEdit {
            get {
                return ResourceManager.GetString("LogEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited category 3D {0}.
        /// </summary>
        public static string LogEditCategory3D {
            get {
                return ResourceManager.GetString("LogEditCategory3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited category PDF {0}.
        /// </summary>
        public static string LogEditCategoryPDF {
            get {
                return ResourceManager.GetString("LogEditCategoryPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited Gallery 3D {0}.
        /// </summary>
        public static string LogEditGallery3D {
            get {
                return ResourceManager.GetString("LogEditGallery3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited Master 3D {0}.
        /// </summary>
        public static string LogEditMaster3D {
            get {
                return ResourceManager.GetString("LogEditMaster3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited master media {0}.
        /// </summary>
        public static string LogEditMasterMedia {
            get {
                return ResourceManager.GetString("LogEditMasterMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited master pdf {0}.
        /// </summary>
        public static string LogEditMasterPDF {
            get {
                return ResourceManager.GetString("LogEditMasterPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited module {0}.
        /// </summary>
        public static string LogEditModule {
            get {
                return ResourceManager.GetString("LogEditModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited project {0}.
        /// </summary>
        public static string LogEditProject {
            get {
                return ResourceManager.GetString("LogEditProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited role {0}.
        /// </summary>
        public static string LogEditRole {
            get {
                return ResourceManager.GetString("LogEditRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited user {0}.
        /// </summary>
        public static string LogEditUser {
            get {
                return ResourceManager.GetString("LogEditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed logged into system..
        /// </summary>
        public static string LogLoginFailed {
            get {
                return ResourceManager.GetString("LogLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully logged into system..
        /// </summary>
        public static string LogLoginSucceed {
            get {
                return ResourceManager.GetString("LogLoginSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully signout from system.
        /// </summary>
        public static string LogSignoutSucceed {
            get {
                return ResourceManager.GetString("LogSignoutSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View {0} List.
        /// </summary>
        public static string LogViewIndex {
            get {
                return ResourceManager.GetString("LogViewIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master media gagal dihapus.
        /// </summary>
        public static string MasterMediaDeleteFailed {
            get {
                return ResourceManager.GetString("MasterMediaDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master media sudah berhasil dihapus.
        /// </summary>
        public static string MasterMediaDeleteSuccess {
            get {
                return ResourceManager.GetString("MasterMediaDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media gagal disimpan.
        /// </summary>
        public static string MediaFailToBeSaved {
            get {
                return ResourceManager.GetString("MediaFailToBeSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media sudah berhasil disimpan.
        /// </summary>
        public static string MediaHasBeenSavedSuccessfully {
            get {
                return ResourceManager.GetString("MediaHasBeenSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modul gagal dihapus.
        /// </summary>
        public static string ModuleDeleteFailed {
            get {
                return ResourceManager.GetString("ModuleDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modul sukses dihapus.
        /// </summary>
        public static string ModuleDeleteSucceed {
            get {
                return ResourceManager.GetString("ModuleDeleteSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password and confirm new password does not match.
        /// </summary>
        public static string NewPasswordInvalid {
            get {
                return ResourceManager.GetString("NewPasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password is invalid.
        /// </summary>
        public static string OldPasswordInvalid {
            get {
                return ResourceManager.GetString("OldPasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Please Select -.
        /// </summary>
        public static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role gagal dihapus.
        /// </summary>
        public static string RoleDeleteFailed {
            get {
                return ResourceManager.GetString("RoleDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role sudah dihapus.
        /// </summary>
        public static string RoleDeleteSucceed {
            get {
                return ResourceManager.GetString("RoleDeleteSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anda tidak memiliki akses terhadap halaman ini.
        /// </summary>
        public static string UnauthorizedAccess {
            get {
                return ResourceManager.GetString("UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User sudah dihapus dari sistem.
        /// </summary>
        public static string UserDeleted {
            get {
                return ResourceManager.GetString("UserDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username {0} already exist in the system.
        /// </summary>
        public static string UsernameExist {
            get {
                return ResourceManager.GetString("UsernameExist", resourceCulture);
            }
        }
    }
}
